### PR TITLE
30 extract excelusing poi

### PR DESCRIPTION
**Pull request by orhlulu**
Roger/Shaojie have used GEMFile feature and merge it to excel and csv tika extraction. 
Can check

### CODE REVIEW

**Comment by shaojieyew** [comment]
I have the below exception when trying to extract data from .xls file
```
org.apache.tika.exception.TikaException: Error creating OOXML extractor
	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:218)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:113)
	at innohack.gem.example.tika.TikaExcelParser.parseExcel(TikaExcelParser.java:40)
	at innohack.gem.entity.gem.data.ExcelFeature.extract(ExcelFeature.java:55)
	at innohack.gem.entity.GEMFile.extractExcel(GEMFile.java:204)
	at innohack.gem.entity.GEMFile.main(GEMFile.java:221)


Caused by: org.apache.poi.openxml4j.exceptions.OLE2NotOfficeXmlFileException: The supplied data appears to be in the OLE2 Format. You are calling the part of POI that deals with OOXML (Office Open XML) Documents. You need to call a different part of POI to process this data (eg HSSF instead of XSSF)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHelper.java:147)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:175)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:104)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:307)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:111)
	... 5 more
```

**Comment by shaojieyew** [comment]
Added issue #50

**Comment by yclim** [comment]
Some suggestion to work on:
- code that are not use in the `GEMFile.extract()` exection path (i.e not run in production) move to `innohack.gem.example` package.  Code in example package will not be reviewed to save time
   -  e.g `innohack.Util.FileUtil`
- utility code that need to be reuse across Features (e.g CsvFeature,  ExcelFeature) goes to a seperate` innohack.gem.util.FeatureExtractorUtil.java` file. 
- keep all  method  in  FeatureExtractorUtil class **MUST** be  static to improve readability. We can  break it to seperate XXXFeatureExtractorUtil  later in seperate issue if needed.
- Combine `ExcelFeature` with `ExcelSheetFeature`. public data expose by XXXFeature class  **MUST** be java types only. So `private List<ExcelSheetFeature> sheetFeatures;` is no good. Could use `Map<String, List<List<String>>> sheetTable ` where `String` = sheetname  and `List<List<String>>` is the table data
- `CsvFeature` to keep it  simple, expose a ` List<List<String>> table`  should be sufficient. by using colMapper  and colRecords, we already assumed that the csv have a header. We could add a getHeader to table.get(0) if we want. Same concept goes to ExcelFeature.
- In your extraction code, don't handle exception (try, catch),  add as method signature and throw upwards. Let  `GemFile.extract()` decide centrally how to  deal with later. `GemFile.extract()` need to add` throws Exception`  signature for this
- add a separate issue for unit test cases. this is important code that we need it to be reliable.

Try to keep issue scope as small as possible to avoid a lot of rework. for e.g this issue could broken down to at least 2 issues, 'Implement CsvFeature' and 'Implement ExcelFeature'.

**Comment by orhlulu** [comment]
> Some suggestion to work on:
> 
> * code that are not use in the `GEMFile.extract()` exection path (i.e not run in production) move to `innohack.gem.example` package.  Code in example package will not be reviewed to save time
>   
>   * e.g `innohack.Util.FileUtil`
CT: > ok done shifted out the fileutil into example.. however for those under tika, i might need to shift back into main gem because they will be used for metadata extraction. This one can be parked in later issues.
> * utility code that need to be reuse across Features (e.g CsvFeature,  ExcelFeature) goes to a seperate` innohack.gem.util.FeatureExtractorUtil.java` file.
> * keep all  method  in  FeatureExtractorUtil class static to improve readability. We can  break it to seperate XXXFeatureExtractorUtil  later in seperate issue if needed.
> * Combine `ExcelFeature` with `ExcelSheetFeature`. public data expose by XXXFeature class  **MUST** be java types only. So `private List<ExcelSheetFeature> sheetFeatures;` is no good. Could use `Map<String, List<List<String>>> sheetTable ` where `String` = sheetname  and `List<List<String>>` is the table data
> * `CsvFeature` to keep it  simple, expose a ` List<List<String>> table`  should be sufficient. by using colMapper  and colRecords, we already assumed that the csv have a header. We could add a getHeader to table.get(0) if we want. Same concept goes to ExcelFeature.
> * In your extraction code, don't handle exception (try, catch),  add as method signature and throw upwards. Let  `GemFile.extract()` decide centrally how to  deal with later. `GemFile.extract()` need to add` throws Exception`  signature for this

CT:> ok done a big refactoring of the codes base and joined both excel and excelsheet features into a single class

> * add a separate issue for unit test cases. this is important code that we need it to be reliable.
> 
CT:> ok will add in new issues for testing later on
> Try to keep issue scope as small as possible to avoid a lot of rework. for e.g this issue could broken down to at least 2 issues, 'Implement CsvFeature' and 'Implement ExcelFeature'.
> 
> @neojunjie FYI if you are working on AbstractFeature

**Comment by yclim** [comment]
added two more refactoring commits 
64a53b54d775fde17e87ea19d7924c22f4fd84b9
a4784f338918266aa98a1384d8c905ba5dd4f1c3

**Pull request merged**
