### PR TITLE
Allow upload and import the spec file

### LINKED ISSUE #128: Implement import spec
To complement #127? Depends on #127

### PR DESCRIPTION
**Pull request by onegang**
Closes #128. This imports the spec file exported by #127. (Quite a high chance this will go into conflict due to so many live PRs....)

@yclim I just placed in a basic file upload in the UI. Feel free to prettify it.

### CODE REVIEW

**Comment by yclim** [comment]
this have conflict too

**Comment by onegang** [comment]
@yclim Fixed the conflicts (due to merging the export spec).

**Comment by onegang** [comment]
importSpec

@yclim  I noticed that you moved the export spec to a separate tab... maybe you can shift the UI functionality to your new tabs? (currently they are still at Configure groups as seen in this screenshot) I will also add the project entity to follow your model...

**Comment by onegang** [comment]
@yclim Added the project entity (based on the new import/export spec tab UI)... but kinda weird that only export/import deals with project while using the app as-is does not have any notion of project (e.g. when is project name used?) If no need, I could drop the project.

**Comment by yclim** [comment]
its good. easier to convert to JSON. I'm thinking that each project can contains 
- one-to-many groups, and each group have
  - one-to-many rules
  - one extractor config (i.e table details, extractor details, and optional timestamp columns)
- the project name and other metadata,
- version

**Pull request merged**
