### PR TITLE
4 jenkins

### LINKED ISSUE #4: CI/CD: Jenkins
Fund a tiny jenkins instance at aws?

### PR DESCRIPTION
**Pull request by onegang**
@all Jenkins is back alive! (Upgraded to small instance... 2 GB RAM should survive now!) Have also added some fixes as master branch has compile errors. The Jenkins URL is added in Readme.

closes #4

### CODE REVIEW

**Comment by yclim** [comment]
merge #58  should fix all compile error

**Comment by onegang** [comment]
> merge #58 should fix all compile error

@yclim The tslint is still failing because of the (x) parameter. Is it ok to remove it? 

On a related note, do we want to explore using Travis CI instead? (it's... FREE!) I cannot hook up this repo to Travis as not enough access rights (think need admin rights)

**Comment by onegang** [comment]
Can one of the admins verify this patch?

**Comment by onegang** [comment]
run tests

**Comment by yclim** [comment]
nice! i did see the tslint error on my end. is it still there?

**Comment by onegang** [comment]
> nice! i did see the tslint error on my end. is it still there?

Yes, my local builds fine, but Jenkin refuses the '(' character...
```
[INFO] --- frontend-maven-plugin:1.7.6:yarn (yarn lint) @ gem ---
[INFO] Running 'yarn lint' in /var/jenkins_home/workspace/GEMS-CI/app
[INFO] yarn run v1.22.4
[INFO] $ tslint --project . src/**/*.ts(x)?
[ERROR] /bin/sh: 1: Syntax error: "(" unexpected
[ERROR] error Command failed with exit code 2.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

I lazily just removed that `(x)`... now, on close look, I think you are trying to do a regex to atch ts and tsx... I changed the regex slightly to make it work on Jenkins too.... will be issuing another PR...

**Pull request merged**
